module.exports = {
    owner : ['94761539856'],
    premium : ['94761539856'],
    ownernomer : '94761539856',
    ownername : 'Dark_Ezio',
    botname : 'Ai_Dark_Ezio_Wa-Bot',
    footer : '©Subadra_Poshitha',
    ig : 'https://github.com/aidarkezio',
    region : 'India, South India, Kerala',
    sc : 'https://github.com/AiDarkEzio/Whats-Bot.git',
    myweb : 'https://www.youtube.com/channel/UCeDeaDD8dpdMT2gO3VHY1JQ',
    packname : 'Ai_Dark_Ezio_Wa-Bot',
    author : 'Dark_Ezio',
    sessionName : 'session',
    prefa : ['','!','.','🐦','🐤','🗿'],
    sp : 'aidarkezio.github.io',
    mess : {
        success: 'Done ✓',
        admin: 'This Feature Is Only For Admin!',
        botAdmin: 'Bot Must Be Admin First!',
        owner: 'This Feature Is Only For Owner!',
        group: 'Feature Used Only For Groups!',
        private: 'Features Used Only For Private Chat!',
        bot: 'This Feature Is Only For Bot',
        wait: 'Wait A minute...',
        error: 'Error! Maybe Api Key Is Expired🤔!',
        endLimit: 'Your Daily Limit Has Expired, The Limit Will Be Reset Every 12 Hours',
    },
    YOUR_API_KEY : 'sanzychan01',
    APIs : {
        zenz: 'https://zenzapis.xyz',
    },
    D_E_DPC: 'https://raw.githubusercontent.com/AiDarkEzio/Whats-Bot/master/GojoMedia/D_E-DPC.jpg',
    D_E_TMB: 'https://raw.githubusercontent.com/AiDarkEzio/Whats-Bot/master/GojoMedia/D_E-TMB.jpg',
    D_E_DP_: 'https://raw.githubusercontent.com/AiDarkEzio/Whats-Bot/master/GojoMedia/D_E-DP.jpg',
    SEND_REED: false,
    //-------
    _qure: '&query=',
    _api2_key2: '4b412c',
    _api_key2: 'chan01',
    _dl: 'downloader/',
    _api: '?apikey=',
    _url: '&url=',
    _api_url: 'https://zenzapis.xyz/',
    _api2_key1: '4e5963',
    _api_key1: 'sanzy'
}

