module.exports = {
    owner : ['94775792013'],
    premium : ['94775792013'],
    ownernomer : '94775792013',
    ownername : 'VIMUKTHI_OSHADA',
    botname : 'Mr.SATHAN',
    footer : 'V I M U K T H I',
    ig : 'https://github.com/oshadaXD',
    region : 'Sri Lanka',
    sc : 'https://github.com/oshadaXD',
    myweb : 'https://www.youtube.com/c/SINHALACARTOONSツ',
    packname : 'Sticker By',
    author : 'SATHAN',
    sessionName : 'session',
    prefa : ['','!','.','🐦','🐤','🗿'],
    sp : 'oshada.ga',
    hint: 'FRUIT GOLF walmart usa VISA % GOLF 2 nut 2 usa tokyo 5 drip korean LAPTOP',
    mess : {
        success: 'Done ✓',
        admin: 'This Feature Is Only For Admin!',
        botAdmin: 'Bot Must Be Admin First!',
        owner: 'This Feature Is Only For Owner!',
        group: 'Feature Used Only For Groups!',
        private: 'Features Used Only For Private Chat!',
        bot: 'This Feature Is Only For Bot',
        wait: 'Wait A minute...',
        error: 'Error! Maybe Api Key Is Expired🤔!',
        endLimit: 'Your Daily Limit Has Expired, The Limit Will Be Reset Every 12 Hours',
    },
    YOUR_API_KEY : '92170802cb1a',
    APIs : {
        zenz: 'https://zenzapis.xyz',
    },
    D_E_DPC: 'https://raw.githubusercontent.com/AiDarkEzio/Whats-Bot/master/GojoMedia/D_E-DPC.jpg',
    D_E_TMB: 'https://raw.githubusercontent.com/AiDarkEzio/Whats-Bot/master/GojoMedia/D_E-TMB.jpg',
    D_E_DP_: 'https://raw.githubusercontent.com/AiDarkEzio/Whats-Bot/master/GojoMedia/D_E-DP.jpg',
    SEND_REED: false,
    //-------
    _qure: '&query=',
    _api2_key2: '4b412c',
    _api_key2: 'chan01',
    _dl: 'downloader/',
    _api: '?apikey=',
    _url: '&url=',
    _api_url: 'https://zenzapis.xyz/',
    _api2_key1: '4e5963',
    _api_key1: 'sanzy'
}

